
[colors]
  [colors.primary] 
    background = "#000000"

[window]
dynamic_padding = false
opacity = 0.8

[window.padding]
x = 5
y = 5


[font]
size = 11

normal = { family = "JetBrainsMono Nerd Font" }

[general]
live_config_reload = true
